apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: /Users/garrettsweeney/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 13 Feb 2021 19:40:19 EST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: cluster_info
    server: https://127.0.0.1:55000
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 13 Feb 2021 19:40:19 EST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: minikube
  user:
    client-certificate: /Users/garrettsweeney/.minikube/profiles/minikube/client.crt
    client-key: /Users/garrettsweeney/.minikube/profiles/minikube/client.key
